### ISSUE TITLE
handleCurlError method incorrect name

### ISSUE THREAD

**Issue by ghost** [vhx/vhx-php#10]
Version 1.4.0 
In lib\Resource.php on line 113 there is a call to “self::_handleCurlError”, but the method in the same class is named “handleCurlError” (without the underscore)

**Comment by scottusrobus** [comment]
thanks @selfrealizationfellowship for reporting this!

PR: https://github.com/vhx/vhx-php/pull/12/

Patched in v1.4.1
See https://github.com/vhx/vhx-php/releases/tag/v1.4.1
