### ISSUE TITLE
Variable “msg” was missing $

### ISSUE THREAD

**Issue by ghost** [vhx/vhx-php#11]
Version 1.4.0
In method handleCurlError, Variable “msg” is missing $: 
“throw new Error\Connection(msg, 408);”

**Comment by scottusrobus** [comment]
thanks again @selfrealizationfellowship!

PR: https://github.com/vhx/vhx-php/pull/12/

Patched in v1.4.1
See https://github.com/vhx/vhx-php/releases/tag/v1.4.1
