### ISSUE TITLE
Constant instead of local variable

### ISSUE THREAD

**Issue by cyrano198** [vhx/vhx-php#15]
The function that handles CURL errors in Resource.php passes the message as a constant and not as a local variable. Please replace msg with $msg.

**Comment by scottusrobus** [comment]
@cyrano198 sorry i missed responding to this one as well.

this was fixed earlier this year as of https://github.com/vhx/vhx-php/releases/tag/v1.4.1. If you update or instance of the vhx library to that or later (latest is v1.6.0) you won't see these issues.

**Comment by scottusrobus** [comment]
for reference, here's the commit
https://github.com/vhx/vhx-php/commit/5d110f13326ec28045fb0b39be276329cc9bb075
