### ISSUE TITLE
PHP 7 compatibility

### ISSUE THREAD

**Issue by douglsmith** [vhx/vhx-php#20]
I ran a compatibility checker in preparing to move to PHP 7. It generated this error:

FILE: /lib/vhx-php-1.5.1/lib/Resource.php

7 | ERROR | 'resource' is a reserved keyword as of PHP version 7.0 and cannot be used to name a class, interface or trait or as part of a namespace (T_CLASS)

**Comment by scottusrobus** [comment]
Thanks for the reminder on this! We will work towards a new release of the client library in the next few days.

**Comment by scottusrobus** [comment]
Latest release should now be PHP 7 compatible.
https://github.com/vhx/vhx-php/releases/tag/v1.9.0
