### ISSUE TITLE
API unable to authorise request with the API key

### ISSUE THREAD

**Issue by allentcm** [vhx/vhx-php#21]
All my request fail due to authorisation failure and get the error message "Api::UnauthorizedException (401)".

I have to manual add the following code in the curl request in the Resource.php:
`curl_setopt($curl, CURLOPT_HTTPHEADER, array(
        "authorization: Basic " . Api::$key,
      ));`
to make the API work.

I am using PHP 7.0.5, Laravel 5.3, php-curl 7.35.0

**Comment by scottusrobus** [comment]
Hi @allentcm are you first setting the API key via the `setKey` method?

`\VHX\Api::setKey('your VHX API key');`

http://dev.vhx.tv/docs/api/?php#authentication

This also could be a compatibility issue, as the client library does not currently support PHP 7. Working on an update!

**Comment by scottusrobus** [comment]
The latest version of the client library is out.
https://github.com/vhx/vhx-php/releases/tag/v1.9.0

Any issues related to PHP 7 should no longer be present. Let us know if you continue to see trouble, even after setting the API key with the `setKey` method.

**Comment by allentcm** [comment]
Hi @scottusrobus, I did set the API key via the setKey method and I confirmed that by reading the API key via the method `\VHX\Api::$key;`. However I still get the error same error message "Api::UnauthorizedException (401)".

**Comment by scottusrobus** [comment]
Hi @allentcm. Thanks for the info. We haven't seen something like this before, so I'm not quite sure what the issue could be. What call are you trying to make? Mind posting your full code (except your api key) here? 

You could also try creating a new API key from your platform dashboard, and re-try with the new one, just to eliminate a miscopied key as a possibility.

**Comment by allentcm** [comment]
Hi @scottusrobus I has discovered that I am actually passing in the API key that has been converted to base64 so resulting the error in authorisation process. I used a new API key and it is working now. Thank you.

**Comment by scottusrobus** [comment]
Gotcha! Thanks @allentcm for the update and glad you were able to figure it out!
